# Generated by Django 3.2.7 on 2021-10-27 01:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0004_alter_testimonials_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonials',
            name='rate',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
